version: "3.2"

services:
  db:
    container_name: seniorbank_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: seniorbank
    ports:
      - "5690:5432"
